language: python
python:
  - 3.6
  
install:
  # Install a newer version of  Pandoc
  - wget wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
  - pandoc --version
  - sudo apt-get -f install
  # Install TeXLive and Jekyll
  - sudo apt-get install -y texlive-full jekyll
  # Install Python requirements
  - pip install -r requirements.txt

script:
  # Clone repo
  - git clone https://${GITHUB_TOKEN}@github.com/citation-file-format/citation-file-format.github.io.git --branch master _site
  # Build PDFs
  - python build-pdfs.py
  # Build the Jekyll site
  - bash travis-build.sh

exclude: [vendor]

sudo: required

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TrWcLYkitJJABuRUefiaYDqUTtbwJFXKbf8FNectqqSux9YytK8DA6J8pAGOeXcx5pAwP/ehhjthlwvjeh4gNLTlRoLNaXZ5nk2vv7sQnMY8X2p6/3juFnl/R2pxb+OrsJ4YyH2RV+JxNz/IxQiEloLnSxuSLLeuvkQYIhWb+rM0wW7KtL7aOz0eNkq9p7aYoPTfOFmVtDraC/2dzw45UAktmvuYl/io4csH4hSXSyv9KA5qZigIYcud0QkFcdzZUYAXudTkL3K6uIO2pPIXhiCJs4IYNZmiztADmI/8kVXifoC7ooN1BSwmVyyVqNcVa90rMI5ok7PKFW7AOOGeR1wBBJYz+4VIp7MnSTzIkAZkXaWC1PDMrqNYBK6EWOUv9ctQjzJNWygVUembQdlAIDGhykhQx3Rdkn3s353SQrcUybwzU9sq/vv1H/NFxNYMEL9VDeZaPD5+UTcomDhzgkfkv5veE4yPaOjjFTZBGGIVMnM5Uu4uo0DKdsh0XxmdY9WUMV5VGtZBiRsNy7Yjm0ibE8E7Q/fyzkCcuHVk//mBNzM062EGKRGqFbd1/jJ7ASjKA3JPkmOmmL7Fhh4tk6oG9aEVkT8oMkV0HiTrTjyP3iuaR6b3cDZR5xfv7X6J0nkCaQEKYZ7EZF/JsxcHaAIGEjxWzQV2eb+G0fxm0VA=
  file: 
    - './_site/assets/pdf/cff-specifications-1.0.3.pdf'
  on:
    tags: true
